### ISSUE TITLE
[Dev] UI fixes in  Admin Rooms Page

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#554]
Fix the following issues identified by UI/UX team

- [x] Additional information title placeholder should be corrected as "Enter Additional Information 
- [x] Room details text should be Align to the other boxes 
- [ ] Put Title, Subtitle, Description title and description in a box 
- [x] [Image Upload Submit Button] Corner Radius should be in 8
- [x]  [Image Upload Submit Button]Hover should be in #192959 
- [x] [Image Upload Submit Button] Text should be "Submit" 
- [ ] Gallery Text should be placed outside of the box 
- [x] Title" Additional information title should be in BOLD 
- [x] Additional Information Description should be BOLD 
- [ ] Remove the Enter category name  text field under category title 
- [ ] Towels placeholder text should be update for the "Tags" 
- [x] Close Button Outline color should be in #5B5959 
- [x] Close Button Hover should be in #192959 
- [x] Close Button text should be in "Close" 
- [x] Save Button Hover should be in #192959 
- [x] Save Button text should be in "Save" 
- [ ] Margin should be add to the bottom of the page

Connect with @BupendraDhyan for any explanation.
